version: "3.9"

services:
    goodmusic:
        container_name: goodmusic
        image: goodmusic
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        expose:
            - "${PORT}"